int8 body_id
int8 data_type
int16 data_length
int64 command_id
int64 frame_time_stamp
float64[] data_array
---
int32 result
int64 command_id
int64 end_time
geometry_msgs/Pose pose
---
int64 command_id
int16 int_lenth
int16 float_length
int32[] int_data_array
float64[] float_data_array