# DualArm.action 

uint8 STATUS_PLANNING = 0   # 规划中
uint8 STATUS_EXECUTING = 1  # 执行中
uint8 STATUS_DONE = 2       # 完成

uint8 ARM_LEFT = 0    # 左臂
uint8 ARM_RIGHT = 1   # 右臂
uint8 ARM_DUAL = 2    # 双臂

uint8 arm_type                       # 运动臂类型 | ARM_LEFT/ARM_RIGHT/ARM_DUAL
interfaces/ArmMotionParams[] arm_motion_params   # 每条手臂的运动参数
float64 velocity_scaling             # 速度缩放因子  [0,1] 
float64 acceleration_scaling         # 加速度缩放因子 [0,1] 
float64 cartesian_step               # MOVEL步长 m [0,0.5] 

---

bool success                         # 执行是否成功
string message                       # 结果描述
float64 final_progress               # 最终进度  [0,1]

---

float64 progress                     # 实时进度  [0,1]
uint8 status                         # 实时状态  STATUS_PLANNING/STATUS_EXECUTING/STATUS_DONE
float64[] joints_left                # 左臂当前关节角（弧度）
float64[] joints_right               # 右臂当前关节角（弧度）

